import Head from 'next/head'
import Image from 'next/image'
import styles from '../sass/Home.module.scss'
import Navbar from '../src/components/Navbar'

import LogoAluclass from '../src/images/logoAluclass.jpg'

export default function CatProdutos() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">Categoria de Produtos</a>
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src={LogoAluclass} alt="Logo Aluclass" width={100} height={100} />
          </span>
        </a>
      </footer>
    </div>
  )
}
